### ISSUE TITLE
Try using VisualStudioWorkspace instead of DTE.Solution

### ISSUE THREAD

**Issue by jcansdale** [mrlacey/StringResourceVisualizer#11]
I wonder if it would make sense to use `VisualStudioWorkspace` instead of `DTE.Solution`?

I don't know for sure, but I think `VisualStudioWorkspace` might be thread safe. This would mean you could do some stuff on a background thread.

I only know about `VisualStudioWorkspace` from playing with this:
https://github.com/jcansdale/SnippetColorizer
(this also shows a way to test `FindResourceFilesAsync` below)

Here is what an implementation might look like. Add a NuGet reference to `Microsoft.VisualStudio.LanguageServices` (`v2.9.0` or less for VS 2017). `AsyncPackage` implements  `IAsyncServiceProvider `, so you can pass this method your package:
```cs
        private static async Task<List<string>> FindResourceFilesAsync(
            Microsoft.VisualStudio.Shell.IAsyncServiceProvider asyncServiceProvider)
        {
            // Run using the thread pool
            await TaskScheduler.Default;

            // Get the VisualStudioWorkspace from MEF
            var componentModel = await asyncServiceProvider.GetServiceAsync(typeof(SComponentModel)) as IComponentModel;
            Assumes.NotNull(componentModel);
            var visualStudioWorkspace = componentModel.GetService<VisualStudioWorkspace>();
            Assumes.NotNull(visualStudioWorkspace);

            var resourceFiles = new List<string>();
            foreach (var project in visualStudioWorkspace.CurrentSolution.Projects)
            {
                foreach (var document in project.Documents)
                {

                    var postfix = ".Designer.cs";
                    var filePath = document.FilePath;

                    if (!filePath.EndsWith(postfix))
                    {
                        continue;
                    }

                    var resxFile = filePath.Substring(0, filePath.Length - postfix.Length) + ".resx";
                    if (!File.Exists(resxFile))
                    {
                        continue;
                    }

                    if (Path.GetFileNameWithoutExtension(resxFile).Contains("."))
                    {
                        // Only want neutral language ones, not locale specific versions
                        continue;
                    }

                    resourceFiles.Add(resxFile);
                }
            }

            return resourceFiles;
        }
```

**Comment by mrlacey** [comment]
@jcansdale Did you have your example of `FindResourceFilesAsync` working? the call to `asyncServiceProvider.GetServiceAsync` is failing for me

**Comment by jcansdale** [comment]
@mrlacey,

Here we go:
https://github.com/jcansdale/StringResourceVisualizer/tree/spike/VisualStudioWorkspace

I haven't tested it much, so I could well be missing something. 😉 

Unfortunately it can't see the `.resx` files directly, to it finds them relative to `.Designer.cs`.

Here's how you can test it.

![image](https://user-images.githubusercontent.com/11719160/48727731-f64fb300-ec2a-11e8-9ca6-ce495f70339d.png)

Just grab the latest from here:
https://marketplace.visualstudio.com/items?itemName=JamieCansdale.TestDrivenNet

**Comment by jcansdale** [comment]
@mrlacey,

I was wondering if the low-tech approach of initially using, `Directory.GetFiles(solutionDir, "*.resx", SearchOption.AllDirectories)` and then `FileSystemWatcher` to detect changes would work?

You'd then only need to query specific .resx file locations and could avoid enumerating all files when a solution loads.

**Comment by mrlacey** [comment]
> @mrlacey,
> 
> I was wondering if the low-tech approach of initially using, `Directory.GetFiles(solutionDir, "*.resx", SearchOption.AllDirectories)` and then `FileSystemWatcher` to detect changes would work?
> 
> You'd then only need to query specific .resx file locations and could avoid enumerating all files when a solution loads.

That seems a great idea. I'll give it a try as it might make things a lot simpler.

**Comment by mrlacey** [comment]
Implementing the file system based search for finding resx files first, so can quickly release an update that removes the blocking issue.
Will use FileSystemWatcher for detecting changes later, as part of other changes.

**Comment by mrlacey** [comment]
[V1.2 is now in the marketplace](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.StringResourceVisualizer) and searches for files using the file system and tracks changes via FileSystemWatcher. 
It adds new limitations (such as not handing projects/files that aren't in the same (or sub) folder as the solution file) but addresses the original issue of not supporting some project types and avoids difficulty with accessing the structure of different project types via the VSSDK.
