### ISSUE TITLE
It should ignore Properties.Settings

### ISSUE THREAD

**Issue by zhangxinxu1992** [mrlacey/StringResourceVisualizer#25]
Please see the snapshot, I believe it should not show an empty line above the Settings property.

![image](https://user-images.githubusercontent.com/15168823/52949148-68fd3580-33b6-11e9-812e-ba831782436c.png)

**Comment by mrlacey** [comment]
@zhangxinxu1992 I'm not able to recreate exactly what you're seeing but have found a way that extra padding is being added when it's not needed. I'll address that and hope it is the same issue.

To enable me to try and reproduce exactly what you're seeing, can you tell me:
- What project type is this in?
- Does the solution also contain a resx file called "Settings.resx" or "Default.resx"?

On a related note, would you like to see the default settings values displayed above their usage as the extension does for string resources?

**Comment by mrlacey** [comment]
A fix for this is included in the v1.4 release which is in the marketplace now.
