### ISSUE TITLE
Dont show resource value in cshtml file

### ISSUE THREAD

**Issue by tolkushkin** [mrlacey/StringResourceVisualizer#26]
### Installed product versions
- Visual Studio: [example 2019 RC4 Professional]
- This extension: [example 1.3]

### Description
Dont show resource value in cshtml file, cshtml it is razor markup, in cs file working properly

### Steps to recreate
1. just use resource in cshtml

### Current behavior
Dont show resource value in cshtml file

### Expected behavior
Show resource value in cshtml file

**Comment by mrlacey** [comment]
@tolkushkin But is the resource name used on the page guaranteed to be the same as the resx file name?

 My (limited) knowledge of cshtml files is that the names of identifiers and the way they are used can vary greatly.

This is similar to the reason that I don't (yet) support resw files.

**Comment by tolkushkin** [comment]
I know what compiled site with resource working well, but just don`t show value above resource in editor.

**Comment by mrlacey** [comment]
> Yes, I know what compiled site with resource working well, but just don`t show value above resource in editor.

I'm not sure what you mean.
The issue I have is knowing reliably and consistently how to identify where a resource is being used in a cshtml file.
Without this an inconsistent experience will be provided where some resources aren't shown or resources will show as being used when they're not.

**Comment by mrlacey** [comment]
Re-reading this issue and I think I misunderstood the original request.

hints are showing up in .cshtml files when they shouldn't.

**Comment by mrlacey** [comment]
I am unable to reproduce the issue as described.

Having created an ASP.NET Core Web Application, I can add and use resources in the app just fine.
When referenced in a `*.cs` file the default resource value is shown above usage.
![image](https://user-images.githubusercontent.com/189547/72443717-a1fc8080-37a6-11ea-9fa2-722249c4d66c.png)

When reference is in a `*.cshtml` file the usage is not shown above the line.

![image](https://user-images.githubusercontent.com/189547/72443788-c3f60300-37a6-11ea-9cc7-3866d6af34bb.png)

I have tested with the latest versions of VS 2017 and 2019.

Feel free to reopen if you can provide a simple way to reproduce the issue.

**Comment by mrlacey** [comment]
I suspect this is actually the same issue as #31 which is now being worked on.

Having to introduce a whole new way for the extension to work to support ILocalizer and cshtml files.
