### ISSUE TITLE
How do I force a search for resources in all my solution projects?

### ISSUE THREAD

**Issue by enriquegago** [mrlacey/StringResourceVisualizer#33]
### Installed product versions
- Visual Studio: [ 2017 Professional Edition]
- This extension: [1.5]

### Description
It does not detect resources in all Projects. What should I do to force reload so that I can look for all the projects in my solution?

**Comment by mrlacey** [comment]
There currently isn't a way to force it to [re]load. It tries to find all the files in all the projects in the solution.

Do you have a way to share your project or can you recreate something that reproduces the problem? 
It's possible that you have a scenario that the code currently can't cope with. Off the top of my head, there are a few things that I've not tested and have the potential to cause a problem. Are you using any of these: Git submodules; projects on different physical drives; files on shared network drives; multiple levels of solution folders?

Also check the output pane as that will list the files it finds. e.g.:
![image](https://user-images.githubusercontent.com/189547/75478189-710e8e80-5995-11ea-8926-ae7f2908162b.png)
This may show something that indicates why it might not be finding everything for you.

**Comment by mrlacey** [comment]
Can reopen if more information or a repro is available
