### ISSUE TITLE
Support displaying resources in object initializers

### ISSUE THREAD

**Issue by danlyons-softek** [mrlacey/StringResourceVisualizer#38]
Currently, the resource values do not appear when referenced within an object initializer:
![image](https://user-images.githubusercontent.com/3289668/94850200-3584e880-03ec-11eb-8885-45f4f2eb29cd.png)

**Comment by danlyons-softek** [comment]
While the value was not displayed initially, it started doing so after switching back-and-forth between files ¯\_(ツ)_/¯

**Comment by mrlacey** [comment]
It might be that the extension hadn't loaded when the document was originally loaded into the editor.
Scrolling the document may also add some values that aren't initially displayed.
