### ISSUE TITLE
Rename VSPackage to StringResourceVisualizerPackage

### ISSUE THREAD

**Issue by MagicAndre1981** [mrlacey/StringResourceVisualizer#39]
### Installed product versions
- Visual Studio: 2017
- This extension: 1.6.70

### Description

[VSPackage](https://github.com/mrlacey/StringResourceVisualizer/blob/fa1676d01e3e58f330911322b94b346098aaf309/src/VSPackage.cs#L49) is generic name and it took me some time to understand that this is your extension, so rename it for better recognition.

### Steps to recreate
1. install extension in VS2017
2. start VS2017 and you get error message that  VSPackage failed to load

### Current behavior

error message that  VSPackage failed to load

### Expected behavior

after rename it would show directly that StringResourceVisualizer failed to load. 

You use [VS2019 SDK](https://github.com/mrlacey/StringResourceVisualizer/blob/fa1676d01e3e58f330911322b94b346098aaf309/src/StringResourceVisualizer.csproj#L106) so the well known VisualStudio.Shell.15.0 in Version 16 failed to load error occurred. So lower SDK version or limit VS support in extension manifest to >= VS2019

**Comment by mrlacey** [comment]
I haven't used it on VS2017 for a long time but will take a look.

It seems odd that VS would report the name of the type as the source of the issue, rather than the name of the extension, but I can rename it. 
From memory, this was the default name generated.

**Comment by MagicAndre1981** [comment]
> It seems odd that VS would report the name of the type as the source of the issue, rather than the name of the extension, but I can rename it.

VS reports this generic name:

![vspackage](https://user-images.githubusercontent.com/8274816/131450434-4bff7857-b409-41dd-90b9-889cff8b65b8.png)

VS2017 = 15 and your extension uses the 16 Version which is VS2019 so the loading fails.

**Comment by MagicAndre1981** [comment]
> Closing as the name was previously changed

thanks, later commits make it VS2022 only, so I can no longer use your extension.

**Comment by mrlacey** [comment]
> > Closing as the name was previously changed
> 
> thanks, later commits make it VS2022 only, so I can no longer use your extension.

There is a [separate version for VS2019](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.StringResourceVisualizer2019) but sadly I'm no longer able to build this for earlier versions :(

**Comment by MagicAndre1981** [comment]
> There is a [separate version for VS2019](https://marketplace.visualstudio.com/items?itemName=MattLaceyLtd.StringResourceVisualizer2019) but sadly I'm no longer able to build this for earlier versions :(

that version works. I was confused as you did not changed the ID for the new 2022 version, so VS always offered an update to the 2022 version from the old 2017/2019 version that I had installed.

**Comment by mrlacey** [comment]
@MagicAndre1981 It sounds like you've got this working yourself. As you're the only person asking for this, do you really need me to repeat what you've done so I can publish it too?

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 It sounds like you've got this working yourself. As you're the only person asking for this, do you really need me to repeat what you've done so I can publish it too?

Ok, I also needed to downgrade Microsoft.CodeAnalysis to 2.10.0, now the missing DLL issue is gone. I need to use the version that Rosyln of this VS version uses. Should I can create a PR?
