### ISSUE TITLE
Support for .razor files

### ISSUE THREAD

**Issue by PeterDraex** [mrlacey/StringResourceVisualizer#42]
Hi Matt, do you plan to add support for visualization in `.razor` files?

**Comment by mrlacey** [comment]
Almost there

![image](https://user-images.githubusercontent.com/189547/185943322-c043dd09-92a1-4fc8-8d57-921f5779bb04.png)

**Comment by mrlacey** [comment]
v1.19 is now in the marketplace and greatly improves support for `.cshtml` and `.razor` files.
